### ISSUE TITLE
Sidebar and Header Dark, but chat is still white in 3.3.6 for Mac OS

### ISSUE THREAD

**Issue by Turbogh** [widget-/slack-black-theme#78]
<img width="1019" alt="screen shot 2019-01-17 at 5 49 19 pm" src="https://user-images.githubusercontent.com/9942935/51360500-c5e89180-1a80-11e9-8690-78abe5a0ccb5.png">

**Comment by rtman** [comment]
+1 on win10

**Comment by Waterdrips** [comment]
Hi Both - Iv had to do this fix (change the css url in the code we paste in) in multiple slack versions

https://github.com/widget-/slack-black-theme/issues/62#issuecomment-410256441

always works for me

**Comment by AlexandreCF** [comment]
I was having the same issue with Windows 10 and Slack 3.3.7.
Fix provided by @Waterdrips solved it!

**Comment by rtman** [comment]
that works thanks!

**Comment by rajanski** [comment]
the chat is still white on Linux Ubuntu with Slack 3.3.7 using  https://raw.githubusercontent.com/Nockiro/slack-black-theme/master/custom.css

**Comment by Waterdrips** [comment]
@rajanski - change it for this in both files


`https://raw.githubusercontent.com/Nockiro/slack-black-theme/3ea2efdfb96ccc91549837ab237d57104181bbf8/custom.css 
`

**Comment by A9G-Data-Droid** [comment]
This was fixed five months ago. Why isn't it committed to prod?

**Comment by lupuleasa-core** [comment]
+1

**Comment by Waterdrips** [comment]
the last commit was in may

**Comment by SteveJSzabo** [comment]
@Waterdrips, I replaced the referenced css file in ssb-interop, but I'm still seeing a white chat background (Windows 10, 3.3.7).

**Comment by ice1080** [comment]
@SteveJSzabo Did you do it in index.js as well? It has to be in both places

**Comment by SteveJSzabo** [comment]
@Waterdrips @ice1080 I made a dumb mistake. I was modifying the ssb-interop for the old version. I didn't even consider that they would leave all the old files for the old versions. Changing it in the new version worked like it should. I didn't need to change anything in index.js.

**Comment by MAFiA303** [comment]
I changed the CSS and it worked.. well mostly, there are some text still in grey and I cannot see it, example: the bio when you chat with someone at the top or small texts

**Comment by alikrc** [comment]
same on windows 10
